def normal_info(tit,at,lvl,holo,rare,art,dcd,scrbox,tsz):
    print("Normal Monster")
    print (tit.get())
    print (at.get())
    print (lvl.get())
    print (holo.get())
    print (rare.get())
    print (art)
    print (dcd.get())
    print (scrbox)
    print (tsz.get())
    """print (lvl.get())
    print (lvl.get())
    print (lvl.get())"""
